name: RareItemHunter
main: com.ne0nx3r0.rareitemhunter.RareItemHunter
version: '0.1'
database: false
description: Rare Item Hunter
commands:
    ri:
      description: RareItems commands
permissions:
    rareitemhunter.notifications.boss:
      description: Player is notified when a boss spawns
    rareitemhunter.admin:
      description: Player has permissions to manage the plugin, is notified of admin issues