name: RareItemHunter
main: com.ne0nx3r0.rareitemhunter.RareItemHunter
version: '0.1'
database: false
depend: [RemoteEntities]
description: Rare Item Hunter
commands:
    ri:
      description: RareItems commands
permissions:
    rareitemhunter.*:
      description: Gives access to all RareItemHunter permissions
      children:
        rareitemhunter.admin: true
      default: op
    rareitemhunter.admin:
      description: Player has permissions to manage the plugin, is notified of admin issues
      default: op